service:
  targetPort: 3000

env:
  PORT: 3000
  SNOOTY_DB_NAME: snooty_prod
  SNOOTY_PROD_DB_NAME: snooty_dotcomprd
  POOL_DB_NAME: pool
  SNOOTY_ENV: dotcomprd

envSecrets:
  ATLAS_URI: snooty-data-api

ingress:
  enabled: true
  hosts:
    - snooty-data-api.docs.staging.corp.mongodb.com

resources:
  limits:
    # Testing max
    memory: 12Gi
  requests:
    memory: 1100Mi
