service:
  targetPort: 3000

env:
  PORT: 3000
  # TODO-4117: Change back to staging values
  SNOOTY_DB_NAME: snooty_prod
  SNOOTY_PROD_DB_NAME: snooty_dotcomprd
  POOL_DB_NAME: pool
  SNOOTY_ENV: dotcomprd

envSecrets:
  # TODO-4117: Change back to staging
  ATLAS_URI: snooty-data-api

ingress:
  enabled: true
  hosts:
    - snooty-data-api.docs.staging.corp.mongodb.com

resources:
  limits:
    memory: 2Gi
  requests:
    memory: 1100Mi

probes:
  enabled: true
  path: /liveness
  headers: {}
  liveness:
    httpGet: true
    initialDelaySeconds: 10
    periodSeconds: 60
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 5
  # Determines when the pod is ready to receive traffic
  readiness:
    initialDelaySeconds: 10
    periodSeconds: 30
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3

autoscaling:
  apiVersion: autoscaling/v2
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 60
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0 # scaleUp immediately if conditions met
      policies:
        # 100% of the currently running replicas may at most be added every 60s
        - type: Percent
          value: 100
          periodSeconds: 60
