service:
  targetPort: 3000

env:
  PORT: 3000
  # TODO-4117: Change back to staging values
  SNOOTY_DB_NAME: snooty_prod
  SNOOTY_PROD_DB_NAME: snooty_dotcomprd
  POOL_DB_NAME: pool
  SNOOTY_ENV: dotcomprd

envSecrets:
  # TODO-4117: Change back to staging
  ATLAS_URI: snooty-data-api

ingress:
  enabled: true
  hosts:
    - snooty-data-api.docs.staging.corp.mongodb.com

resources:
  limits:
    memory: 1300Mi
  requests:
    memory: 1100Mi

autoscaling:
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50
